// <auto-generated />
namespace VilaItalia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _27042019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27042019));
        
        string IMigrationMetadata.Id
        {
            get { return "201904272025137_27042019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
